# Generated by Django 6.0.1 on 2026-02-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_drop_address_ride_pickup_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
