# Generated by Django 6.0.1 on 2026-02-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_ride_pickup_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='pickup_address',
        ),
    ]
