# Generated by Django 6.0.1 on 2026-02-24 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_driver_status_alter_driver_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_rides',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricing',
            name='vehicle_type',
            field=models.CharField(choices=[('mini', 'Mini'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('luxury', 'Luxury')], default='sedan', max_length=20),
        ),
        migrations.AddField(
            model_name='ride',
            name='matched_distance_km',
            field=models.FloatField(blank=True, help_text='Distance (km) between pickup and the matched driver at time of matching', null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(choices=[('mini', 'Mini'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('luxury', 'Luxury')], default='sedan', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('mini', 'Mini'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('luxury', 'Luxury')], default='sedan', max_length=20),
        ),
        migrations.AlterField(
            model_name='earning',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('paypal', 'PayPal'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ride',
            name='drop_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='drop_lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='taxi_type',
            field=models.CharField(choices=[('mini', 'Mini'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('luxury', 'Luxury')], max_length=20),
        ),
    ]
