# Generated by Django 5.2.7 on 2026-03-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_addonplan_addonpayment_driveraddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='cancellation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='low_rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
