# Generated by Django 5.2.7 on 2026-03-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_driver_cancellation_count_driver_low_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='requested', max_length=20),
        ),
    ]
