# Generated by Django 5.2.7 on 2026-03-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0014_alter_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
