# Generated by Django 5.2.7 on 2026-03-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0015_driver_suspended_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_card',
            field=models.ImageField(blank=True, null=True, upload_to='verification/license/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='rc_book',
            field=models.ImageField(blank=True, null=True, upload_to='verification/rc_book/'),
        ),
    ]
