# Generated by Django 5.2.7 on 2026-03-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0016_driver_license_card_driver_rc_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
