# Generated by Django 5.2.7 on 2026-03-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0017_driver_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
