# Generated by Django 6.0.1 on 2026-03-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0018_driver_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversubscription',
            name='km_used_today',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='daily_km_limit',
            field=models.IntegerField(default=100),
        ),
    ]
