# Generated by Django 5.2.7 on 2026-03-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0019_driversubscription_km_used_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonplan',
            name='km_limit',
            field=models.IntegerField(default=0, help_text='Extra KM quota granted by this add-on (0 = no KM boost)'),
        ),
        migrations.AlterField(
            model_name='addonplan',
            name='ride_limit',
            field=models.IntegerField(default=0),
        ),
    ]
