# Generated by Django 5.2.7 on 2026-03-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0020_add_km_limit_to_addonplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveraddon',
            name='km_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driveraddon',
            name='km_used',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='driveraddon',
            name='rides_limit',
            field=models.IntegerField(default=0),
        ),
    ]
